import { adminCreateCompany } from "@/app/actions/company";
import { PageHeader } from "@/components/app-shell";
import { Card, EmptyState, Field, Select, SubmitButton, TextArea } from "@/components/ui";
import { requireVerifiedSession } from "@/lib/auth/session";
import { listAllCompanies, listUsers } from "@/lib/data/repository";
import { assertPlatformAdmin } from "@/lib/permissions";

export default async function AdminCompaniesPage() {
  const { user } = await requireVerifiedSession("/admin/companies");
  if (!user) throw new Error("User profile is required.");
  assertPlatformAdmin(user.platformRole);
  const [companies, users] = await Promise.all([listAllCompanies(), listUsers()]);
  const verifiedUsers = users.filter((candidate) => candidate.emailVerified && candidate.status === "Active");

  return (
    <>
      <PageHeader title="Companies" description="Businesses are created manually after external review. ABNs are never generated by the app." />
      <Card className="mb-6">
        <form action={adminCreateCompany} className="grid gap-4 md:grid-cols-2">
          <Field label="Business name" name="businessName" required />
          <Field label="ABN, optional" name="abn" />
          <Field label="Business category" name="businessCategory" required />
          <Field label="Business email" name="businessEmail" type="email" required />
          <Field label="Business phone" name="businessPhone" required />
          <Field label="Website, optional" name="website" />
          <Field label="Business location / service area, optional" name="serviceArea" />
          <label className="grid gap-1.5 text-sm font-medium text-ink">
            Owner account
            <select className="h-10 rounded-md border border-line bg-white px-3" name="ownerUserId" required>
              <option value="">Select a verified user</option>
              {verifiedUsers.map((candidate) => (
                <option key={candidate.id} value={candidate.id}>{candidate.fullName} · {candidate.jobSkill}</option>
              ))}
            </select>
          </label>
          <Select label="Verification status" name="verificationStatus" values={["Unreviewed", "Business details verified", "Rejected"]} />
          <Select label="Company status" name="status" values={["Pending", "Active", "Suspended", "Rejected"]} />
          <div className="md:col-span-2"><TextArea label="Verification notes" name="verificationNotes" /></div>
          <SubmitButton>Create company</SubmitButton>
        </form>
      </Card>
      {companies.length ? (
        <div className="overflow-hidden rounded-lg border border-line bg-white">
          <table className="w-full text-left text-sm">
            <thead className="bg-mist text-ink/60"><tr><th className="p-3">Business</th><th className="p-3">Category</th><th className="p-3">Verification</th><th className="p-3">Status</th></tr></thead>
            <tbody>{companies.map((company) => <tr key={company.id} className="border-t border-line"><td className="p-3 font-medium">{company.businessName}</td><td className="p-3">{company.businessCategory}</td><td className="p-3">{company.verificationStatus}</td><td className="p-3">{company.status}</td></tr>)}</tbody>
          </table>
        </div>
      ) : (
        <EmptyState title="No companies created yet." body="Create a company only after external business approval is complete." />
      )}
    </>
  );
}
